// eslint-disable-next-line import/prefer-default-export
export const types = {
  RESET_FORM: "RESET_FORM",
  SET_JOB: "SET_JOB",
  SET_JOB_TYPES: "SET_JOB_TYPES",
  SET_COUNTRIES: "SET_COUNTRIES",
  SET_CITIES: "SET_CITIES",
  SET_EXPERIENCE: "SET_EXPERIENCE",
  SET_KEY_SKILLS: "SET_KEY_SKILLS",
  SET_SALARY: "SET_SALARY_MAX",
  SET_EDIT_MODE: "SET_EDIT_MODE"
};
