export default {
  LOGIN: "LOGIN",
  logInError: "logInError",
  logInErrorReset: "logInErrorReset",
  SIGNUP: "SIGNUP",
  signUpError: "signUpError",
  signUpErrorReset: "signUpErrorReset",
  LOGOUT: "LOGOUT",
  setSignUpName: "setSignUpName",
  setSignUpsurname: "setSignUpsurname",
  setSignUpEmail: "setSignUpEmail",
  setSignUpPassword: "setSignUpPassword",
  setLogInName: "setLogInName",
  setLogInEmail: "setLogInEmail",
  setLogInPassword: "setLogInPassword",
  setSignUpState: "setSignUpState",
  setLogInState: "setLogInState",
  setWorkGiver: "setWorkGiver",
  setWorkTaker: "setWorkTaker"
};
