export default {
  LOGIN: "LOGIN",
  LOG_IN_ERROR: "LOG_IN_ERROR",
  LOG_IN_ERROR_RESET: "LOG_IN_ERROR_RESET",
  SIGNUP: "SIGNUP",
  SIGNUP_ERROR: "SIGNUP_ERROR",
  SIGNUP_ERROR_RESET: "SIGNUP_ERROR_RESET",
  LOGOUT: "LOGOUT",
  SET_SIGNUP_NAME: "SET_SIGNUP_NAME",
  SET_SIGNUP_EMAIL: "SET_SIGNUP_EMAIL",
  SET_SIGNUP_PASSWORD: "SET_SIGNUP_PASSWORD",
  SET_LOGIN_NAME: "SET_LOGIN_NAME",
  SET_LOGIN_EMAIL: "SET_LOGIN_EMAIL",
  SET_LOGIN_PASSWORD: "SET_LOGIN_PASSWORD",
  SET_SIGNUP_STATE: "SET_SIGNUP_STATE",
  SET_LOGIN_STATE: "SET_LOGIN_STATE",
  SET_ACCOUNT_TYPE: "SET_ACCOUNT_TYPE"
};
