export const types = {
  GET_ALL_OFFERS: "GET_ALL_OFFERS",
  SEARCH: "SEARCH",
  ADD_JOB: "ADD_JOB",
  SET_JOB: "SET_JOB",
  SET_CITY: "SET_CITY",
  SET_EXP_MIN: "SET_EXP_MIN",
  SET_EXP_MAX: "SET_EXP_MAX",
  SET_SALARY_MIN: "SET_SALARY_MIN",
  SET_SALARY_MAX: "SET_SALARY_MAX",
  SET_LOCATION: "SET_LOCATION",
  SELECT_JOB_TYPE: "SELECT_JOB_TYPE",
  SELECT_CITY: "SELECT_CITY",
  SELECT_COUNTRY: "SELECT_COUNTRY",
  SELECT_EXP_MIN: "SELECT_EXP_MIN",
  SELECT_EXP_MAX: "SELECT_EXP_MAX",
  SELECT_SALARY_MIN: "SELECT_SALARY_MIN",
  SELECT_SALARY_MAX: "SELECT_SALARY_MAX"
}