// eslint-disable-next-line import/prefer-default-export
export const types = {
  ADD_JOB: "ADD_JOB",
  TOGGLE_UPDATE_PROFILE: "TOGGLE_UPDATE_PROFILE",

  GET_ALL_OFFERS: "GET_ALL_OFFERS",
  SEARCH: "SEARCH",
  SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",

  GET_ALL_IVENTS: "GET_ALL_IVENTS",
  SEARCH_IVENT: "SEARCH_IVENT",
  SET_SEARCH_IVENT_RESULTS: "SET_SEARCH_IVENT_RESULTS",

  SET_NOTIFICATION: "SET_NOTIFICATION"
};
