// eslint-disable-next-line import/prefer-default-export
export const types = {
  RESET_FORM: "RESET_FORM",
  GET_ALL_OFFERS: "GET_ALL_OFFERS",
  SEARCH: "SEARCH",
  ADD_JOB: "ADD_JOB",
  SET_JOB: "SET_JOB",
  SET_JOB_TYPE: "SET_JOB_TYPE",
  SET_COUNTRY: "SET_COUNTRY",
  SET_CITY: "SET_CITY",
  SET_EXP_MIN: "SET_EXP_MIN",
  SET_EXP_MAX: "SET_EXP_MAX",
  SET_SALARY_MIN: "SET_SALARY_MIN",
  SET_SALARY_MAX: "SET_SALARY_MAX",
  SET_LOCATION: "SET_LOCATION",
  SET_NOTIFICATION: "SET_NOTIFICATION"
};
